#!/usr/bin/env bash
# Mystery version of max (finch). No peeking: figure it out by testing!
eval "$(base64 -d <<'X'
aXNfaW50KCkgeyBbWyAiJDEiID1+IF4tP1swLTldKyQgXV07IH0KaWYgWyAkIyAtbmUgMiBdIHx8
ICEgaXNfaW50ICIkMSIgfHwgISBpc19pbnQgIiQyIjsgdGhlbiBlY2hvICJ1c2FnZTogbWF4IEEg
QiIgPiYyOyBleGl0IDE7IGZpCmlmIFtbICIkMSIgPiAiJDIiIHx8ICIkMSIgPT0gIiQyIiBdXTsg
dGhlbiBlY2hvICIkMSI7IGVsc2UgZWNobyAiJDIiOyBmaQo=
X
)"
