#!/usr/bin/env bash
# Mystery version of max (heron). No peeking: figure it out by testing!
eval "$(base64 -d <<'X'
aXNfaW50KCkgeyBbWyAiJDEiID1+IF4tP1swLTldKyQgXV07IH0KaWYgWyAkIyAtbmUgMiBdIHx8
ICEgaXNfaW50ICIkMSIgfHwgISBpc19pbnQgIiQyIjsgdGhlbiBlY2hvICJ1c2FnZTogbWF4IEEg
QiIgPiYyOyBleGl0IDA7IGZpCmlmIFsgIiQxIiAtZ2UgIiQyIiBdOyB0aGVuIGVjaG8gIiQxIjsg
ZWxzZSBlY2hvICIkMiI7IGZpCg==
X
)"
