#!/usr/bin/env bash
# Mystery version of max (jay). No peeking: figure it out by testing!
eval "$(base64 -d <<'X'
aXNfaW50KCkgeyBbWyAiJDEiID1+IF4tP1swLTldKyQgXV07IH0KaWYgWyAkIyAtbmUgMiBdIHx8
ICEgaXNfaW50ICIkMSIgfHwgISBpc19pbnQgIiQyIjsgdGhlbiBlY2hvICJ1c2FnZTogbWF4IEEg
QiI7IGV4aXQgMTsgZmkKaWYgWyAiJDEiIC1nZSAiJDIiIF07IHRoZW4gZWNobyAiJDEiOyBlbHNl
IGVjaG8gIiQyIjsgZmkK
X
)"
