#!/usr/bin/env bash
# Mystery version of max (wren). No peeking: figure it out by testing!
eval "$(base64 -d <<'X'
aXNfaW50KCkgeyBbWyAiJDEiID1+IF4tP1swLTldKyQgXV07IH0KaWYgWyAkIyAtbmUgMiBdIHx8
ICEgaXNfaW50ICIkMSIgfHwgISBpc19pbnQgIiQyIjsgdGhlbiBlY2hvICJ1c2FnZTogbWF4IEEg
QiIgPiYyOyBleGl0IDE7IGZpCmE9JHsxIy19OyBiPSR7MiMtfQppZiBbICIkYSIgLWdlICIkYiIg
XTsgdGhlbiBlY2hvICIkMSI7IGVsc2UgZWNobyAiJDIiOyBmaQo=
X
)"
